### ISSUE TITLE
安装Croon的时候出错

### ISSUE THREAD

**Issue by dcb9** [hfcorriez/croon#1]
你好，
    我在运行
# composer require croon/croon

Please provide a version constraint for the croon/croon requirement: 

然后我就不知道该输入多少版本号了，上一步 composer install 是成功的。

曾尝试不做这一步，直接使用，新建了一个  croon.list 的文件 使用
# ./bin/croon ../croon.list -l croon.log

PHP Fatal error:  Class 'Pagon\ChildProcess\ChildProcess' not found in /root/croon/src/Croon/Croon.php on line 36

Fatal error: Class 'Pagon\ChildProcess\ChildProcess' not found in /root/croon/src/Croon/Croon.php on line 36

但是我查找了一下这个文件是存在的，
# ls /root/croon/vendor/pagon/childprocess/lib/Pagon/ChildProcess.php

麻烦分析一下是什么问题导致的，我对composer 和 posix 及 pencl 都不是很了解。只是按相关的文档安装上的。

**Comment by dcb9** [comment]
刚才我又试了一下， 

# composer require croon/croon

# Please provide a version constraint for the croon/croon requirement: *

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating autoload files

然后再运行计划任务程序还是出错，错误和之前一样

**Comment by hfcorriez** [comment]
Fixed!

Composer 安装 0.2.0：

https://packagist.org/packages/croon/croon

如果 Composer 用不惯，可以直接下最新的版本：

https://github.com/hfcorriez/croon/releases
