### ISSUE TITLE
记录LOG日志时的一个BUG

### ISSUE THREAD

**Issue by dcb9** [hfcorriez/croon#4]
问题出在auto_write，如果不对这个设置值即采用默认的（false），这时候生成的日志会出现好多冗余数据，每一次的写入都会把以前的信息再加起来，好像是把所有的日志累加起来了，后来我尝试把auto_write设置成了 true 发现这个问题就不存在了。

下面是我的一段实际测试命令，通过wc -l 获取log日志的总行数，可以看出区别。

看了看日志功能的代码，功底太浅，被玩的快走火入魔了。。。。还是看不懂。

``````
$ echo ''>cron.log
$ cat cron.list
* * * * * * ls
$ time bin/croon -l cron.log cron.list
^C
real    0m20.111s
user    0m0.359s
sys 0m0.279s
$ wc -l cron.log
     548 cron.log
$ echo ''>cron.log
$ vim bin/croon
$ # 把 auto_write 设置成了 true
$ time bin/croon -l cron.log cron.list
^C
real    0m19.856s
user    0m0.353s
sys 0m0.317s
/Documents/phpcron$ wc -l cron.log
      65 cron.log```
``````

**Comment by hfcorriez** [comment]
收到

**Comment by hfcorriez** [comment]
你用的哪个版本？

**Comment by dcb9** [comment]
"croon/croon": "0.2.0"

**Comment by dcb9** [comment]
$ grep logger vendor/croon/croon/composer.json
    "pagon/logger": "*",

**Comment by hfcorriez** [comment]
之前用 master 调试没有问题，好奇怪，我再来看看

**Comment by hfcorriez** [comment]
auto_write 「主动写」默认为 false，这是为 Logger 为 web 准备的一个特性，当脚本结束的时候会一起写入到日志。在命令行下，「主动写」只能打开，否则就会造成内存泄漏。这一块后面再优化下 Logger 的自动写机制判断。

**Comment by hfcorriez** [comment]
https://github.com/hfcorriez/croon/releases/tag/0.2.1 使用最新的版本

**Comment by dcb9** [comment]
最新版本的，现在如果在命令行执行，这个问题还存在不？还是说必须要手动指定 auto_write为 true?

**Comment by hfcorriez** [comment]
不需要，已经修改了默认设置！

在 2014年8月4日，17:02，BOB CHENGBIN notifications@github.com 写道：

**Comment by dcb9** [comment]
哦哦好的，这个问题好像好高深，回家升级下再把公司的也更新。
